/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CommunityMessage {
  'author' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface ContactSignup {
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface PeacePledge { 'name' : string, 'message' : string }
export interface PeaceStory {
  'id' : bigint,
  'region' : string,
  'title' : string,
  'imageHint' : string,
  'author' : string,
  'summary' : string,
}
export interface Resource {
  'id' : bigint,
  'typ' : string,
  'url' : string,
  'title' : string,
  'description' : string,
}
export interface WorldInitiative {
  'id' : bigint,
  'latitude' : number,
  'title' : string,
  'country' : string,
  'description' : string,
  'longitude' : number,
}
export interface _SERVICE {
  'getContactSignups' : ActorMethod<[], Array<ContactSignup>>,
  'getNewsletterSignups' : ActorMethod<[], Array<string>>,
  'getPeacePledges' : ActorMethod<[], Array<PeacePledge>>,
  'getPeaceStories' : ActorMethod<[], Array<PeaceStory>>,
  'getRecentCommunityMessages' : ActorMethod<[], Array<CommunityMessage>>,
  'getResources' : ActorMethod<[], Array<Resource>>,
  'getWorldInitiatives' : ActorMethod<[], Array<WorldInitiative>>,
  'postCommunityMessage' : ActorMethod<[string, string], undefined>,
  'signupNewsletter' : ActorMethod<[string], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'submitPeacePledge' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];